// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmemHNKkT0p6dGO6NYUDtvXzZ67QDYohc',
    appId: '1:454716691635:web:555fa81fe96c2327984cc6',
    messagingSenderId: '454716691635',
    projectId: 'alcaldiapp-e9da6',
    authDomain: 'alcaldiapp-e9da6.firebaseapp.com',
    databaseURL: 'https://alcaldiapp-e9da6-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldiapp-e9da6.appspot.com',
    measurementId: 'G-HMK5WMXJ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDklcgcFYk3A5jRKDejQyCyc-Vof-eCYQ',
    appId: '1:454716691635:android:0b9673f54f8768e8984cc6',
    messagingSenderId: '454716691635',
    projectId: 'alcaldiapp-e9da6',
    databaseURL: 'https://alcaldiapp-e9da6-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldiapp-e9da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgY2dlz613G9Hy_FuN3SxsmjW2oJdeGQ',
    appId: '1:454716691635:ios:0e044f92731d5fd9984cc6',
    messagingSenderId: '454716691635',
    projectId: 'alcaldiapp-e9da6',
    databaseURL: 'https://alcaldiapp-e9da6-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldiapp-e9da6.appspot.com',
    androidClientId: '454716691635-4dq1itkokpt4h95t6gmfkbcakaeuhg9j.apps.googleusercontent.com',
    iosClientId: '454716691635-n35j3cda2pmleov6hihcuc6c3ojap5do.apps.googleusercontent.com',
    iosBundleId: 'com.popupbits.flFireAuth',
  );
}
